# Generated by Django 3.2.7 on 2021-09-17 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('filename', models.TextField()),
                ('file', models.FileField(default='default/testAudio.mp3', upload_to='uploads/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Started', max_length=100)),
            ],
        ),
    ]
