# Generated by Django 3.2.7 on 2021-09-28 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_job_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='file',
            field=models.FileField(default='default/testAudio.mp3', upload_to='media/uploads/'),
        ),
        migrations.AlterField(
            model_name='job',
            name='name',
            field=models.CharField(default='967315edcbb1474086e51484b03c541a7809', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
