# Generated by Django 3.2.7 on 2021-11-16 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20210928_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='language',
            field=models.CharField(default='English', max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='file',
            field=models.FileField(default='default/testAudio.mp3', upload_to='uploads/'),
        ),
    ]
