# Generated by Django 3.2.7 on 2021-11-16 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20211116_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='language',
            field=models.CharField(blank=True, default='English', max_length=255),
        ),
    ]
